// <auto-generated />
using Data.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(WorldMoodDbContext))]
    [Migration("20220812094911_AddCountry")]
    partial class AddCountry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.6.22329.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Data.Models.Country", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NameRu")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NameEn")
                        .IsUnique();

                    b.HasIndex("NameRu")
                        .IsUnique();

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            NameEn = "Kazakhstan",
                            NameRu = "Казахстан"
                        },
                        new
                        {
                            Id = 2L,
                            NameEn = "Ukraine",
                            NameRu = "Украина"
                        },
                        new
                        {
                            Id = 3L,
                            NameEn = "Belarus",
                            NameRu = "Беларусь"
                        },
                        new
                        {
                            Id = 4L,
                            NameEn = "Russia",
                            NameRu = "Россия"
                        },
                        new
                        {
                            Id = 5L,
                            NameEn = "Azerbaijan",
                            NameRu = "Азербайджан"
                        },
                        new
                        {
                            Id = 6L,
                            NameEn = "Armenia",
                            NameRu = "Армения"
                        },
                        new
                        {
                            Id = 7L,
                            NameEn = "Georgia",
                            NameRu = "Грузия"
                        },
                        new
                        {
                            Id = 8L,
                            NameEn = "Israel",
                            NameRu = "Израиль"
                        },
                        new
                        {
                            Id = 9L,
                            NameEn = "USA",
                            NameRu = "Соединенные Штаты Америки"
                        },
                        new
                        {
                            Id = 10L,
                            NameEn = "Canada",
                            NameRu = "Канада"
                        },
                        new
                        {
                            Id = 11L,
                            NameEn = "Kyrgyzstan",
                            NameRu = "Киргизия"
                        },
                        new
                        {
                            Id = 12L,
                            NameEn = "Latvia",
                            NameRu = "Латвия"
                        },
                        new
                        {
                            Id = 13L,
                            NameEn = "Lithuania",
                            NameRu = "Литва"
                        },
                        new
                        {
                            Id = 14L,
                            NameEn = "Estonia",
                            NameRu = "Эстония"
                        },
                        new
                        {
                            Id = 15L,
                            NameEn = "Moldova",
                            NameRu = "Молдова"
                        },
                        new
                        {
                            Id = 16L,
                            NameEn = "Tajikistan",
                            NameRu = "Таджикистан"
                        },
                        new
                        {
                            Id = 17L,
                            NameEn = "Turkmenistan",
                            NameRu = "Туркменистан"
                        },
                        new
                        {
                            Id = 18L,
                            NameEn = "Uzbekistan",
                            NameRu = "Узбекистан"
                        },
                        new
                        {
                            Id = 19L,
                            NameEn = "Australia",
                            NameRu = "Австралия"
                        },
                        new
                        {
                            Id = 20L,
                            NameEn = "Austria",
                            NameRu = "Австрия"
                        },
                        new
                        {
                            Id = 21L,
                            NameEn = "Albania",
                            NameRu = "Албания"
                        },
                        new
                        {
                            Id = 22L,
                            NameEn = "Algeria",
                            NameRu = "Алжир"
                        },
                        new
                        {
                            Id = 23L,
                            NameEn = "American Samoa",
                            NameRu = "Американское Самоа"
                        },
                        new
                        {
                            Id = 24L,
                            NameEn = "Anguilla",
                            NameRu = "Ангилья"
                        },
                        new
                        {
                            Id = 25L,
                            NameEn = "Angola",
                            NameRu = "Ангола"
                        },
                        new
                        {
                            Id = 26L,
                            NameEn = "Andorra",
                            NameRu = "Андорра"
                        },
                        new
                        {
                            Id = 27L,
                            NameEn = "Antigua and Barbuda",
                            NameRu = "Антигуа и Барбуда"
                        },
                        new
                        {
                            Id = 28L,
                            NameEn = "Argentina",
                            NameRu = "Аргентина"
                        },
                        new
                        {
                            Id = 29L,
                            NameEn = "Aruba",
                            NameRu = "Аруба"
                        },
                        new
                        {
                            Id = 30L,
                            NameEn = "Afghanistan",
                            NameRu = "Афганистан"
                        },
                        new
                        {
                            Id = 31L,
                            NameEn = "The bahamas",
                            NameRu = "Багамы"
                        },
                        new
                        {
                            Id = 32L,
                            NameEn = "Bangladesh",
                            NameRu = "Бангладеш"
                        },
                        new
                        {
                            Id = 33L,
                            NameEn = "Barbados",
                            NameRu = "Барбадос"
                        },
                        new
                        {
                            Id = 34L,
                            NameEn = "Bahrain",
                            NameRu = "Бахрейн"
                        },
                        new
                        {
                            Id = 35L,
                            NameEn = "Belize",
                            NameRu = "Белиз"
                        },
                        new
                        {
                            Id = 36L,
                            NameEn = "Belgium",
                            NameRu = "Бельгия"
                        },
                        new
                        {
                            Id = 37L,
                            NameEn = "Benin",
                            NameRu = "Бенин"
                        },
                        new
                        {
                            Id = 38L,
                            NameEn = "Bermuda",
                            NameRu = "Бермудские острова"
                        },
                        new
                        {
                            Id = 39L,
                            NameEn = "Bulgaria",
                            NameRu = "Болгария"
                        },
                        new
                        {
                            Id = 40L,
                            NameEn = "Bolivia",
                            NameRu = "Боливия"
                        },
                        new
                        {
                            Id = 41L,
                            NameEn = "Bosnia and Herzegovina",
                            NameRu = "Босния и Герцеговина"
                        },
                        new
                        {
                            Id = 42L,
                            NameEn = "Botswana",
                            NameRu = "Ботсвана"
                        },
                        new
                        {
                            Id = 43L,
                            NameEn = "Brazil",
                            NameRu = "Бразилия"
                        },
                        new
                        {
                            Id = 44L,
                            NameEn = "Brunei Darussalam",
                            NameRu = "Бруней-Даруссалам"
                        },
                        new
                        {
                            Id = 45L,
                            NameEn = "Burkina Faso",
                            NameRu = "Буркина-Фасо"
                        },
                        new
                        {
                            Id = 46L,
                            NameEn = "Burundi",
                            NameRu = "Бурунди"
                        },
                        new
                        {
                            Id = 47L,
                            NameEn = "Butane",
                            NameRu = "Бутан"
                        },
                        new
                        {
                            Id = 48L,
                            NameEn = "Vanuatu",
                            NameRu = "Вануату"
                        },
                        new
                        {
                            Id = 49L,
                            NameEn = "Great Britain",
                            NameRu = "Великобритания"
                        },
                        new
                        {
                            Id = 50L,
                            NameEn = "Hungary",
                            NameRu = "Венгрия"
                        },
                        new
                        {
                            Id = 51L,
                            NameEn = "Venezuela",
                            NameRu = "Венесуэла"
                        },
                        new
                        {
                            Id = 52L,
                            NameEn = "Virgin Islands, British",
                            NameRu = "Виргинские острова, Британские"
                        },
                        new
                        {
                            Id = 53L,
                            NameEn = "Virgin Islands, US",
                            NameRu = "Виргинские острова, США"
                        },
                        new
                        {
                            Id = 54L,
                            NameEn = "East Timor",
                            NameRu = "Восточный Тимор"
                        },
                        new
                        {
                            Id = 55L,
                            NameEn = "Vietnam",
                            NameRu = "Вьетнам"
                        },
                        new
                        {
                            Id = 56L,
                            NameEn = "Gabon",
                            NameRu = "Габон"
                        },
                        new
                        {
                            Id = 57L,
                            NameEn = "Haiti",
                            NameRu = "Гаити"
                        },
                        new
                        {
                            Id = 58L,
                            NameEn = "Guyana",
                            NameRu = "Гайана"
                        },
                        new
                        {
                            Id = 59L,
                            NameEn = "Gambia",
                            NameRu = "Гамбия"
                        },
                        new
                        {
                            Id = 60L,
                            NameEn = "Ghana",
                            NameRu = "Гана"
                        },
                        new
                        {
                            Id = 61L,
                            NameEn = "Guadeloupe",
                            NameRu = "Гваделупа"
                        },
                        new
                        {
                            Id = 62L,
                            NameEn = "Guatemala",
                            NameRu = "Гватемала"
                        },
                        new
                        {
                            Id = 63L,
                            NameEn = "Guinea",
                            NameRu = "Гвинея"
                        },
                        new
                        {
                            Id = 64L,
                            NameEn = "Guinea bissau",
                            NameRu = "Гвинея - Бисау"
                        },
                        new
                        {
                            Id = 65L,
                            NameEn = "Germany",
                            NameRu = "Германия"
                        },
                        new
                        {
                            Id = 66L,
                            NameEn = "Gibraltar",
                            NameRu = "Гибралтар"
                        },
                        new
                        {
                            Id = 67L,
                            NameEn = "Honduras",
                            NameRu = "Гондурас"
                        },
                        new
                        {
                            Id = 68L,
                            NameEn = "Hong Kong",
                            NameRu = "Гонконг"
                        },
                        new
                        {
                            Id = 69L,
                            NameEn = "Grenada",
                            NameRu = "Гренада"
                        },
                        new
                        {
                            Id = 70L,
                            NameEn = "Greenland",
                            NameRu = "Гренландия"
                        },
                        new
                        {
                            Id = 71L,
                            NameEn = "Greece",
                            NameRu = "Греция"
                        },
                        new
                        {
                            Id = 72L,
                            NameEn = "Guam",
                            NameRu = "Гуам"
                        },
                        new
                        {
                            Id = 73L,
                            NameEn = "Denmark",
                            NameRu = "Дания"
                        },
                        new
                        {
                            Id = 74L,
                            NameEn = "Dominica",
                            NameRu = "Доминика"
                        },
                        new
                        {
                            Id = 75L,
                            NameEn = "Dominican Republic",
                            NameRu = "Доминиканская Респблика"
                        },
                        new
                        {
                            Id = 76L,
                            NameEn = "Egypt",
                            NameRu = "Египет"
                        },
                        new
                        {
                            Id = 77L,
                            NameEn = "Zambia",
                            NameRu = "Замбия"
                        },
                        new
                        {
                            Id = 78L,
                            NameEn = "West Sahara",
                            NameRu = "Западная Сахара"
                        },
                        new
                        {
                            Id = 79L,
                            NameEn = "Zimbabwe",
                            NameRu = "Зимбабве"
                        },
                        new
                        {
                            Id = 80L,
                            NameEn = "India",
                            NameRu = "Индия"
                        },
                        new
                        {
                            Id = 81L,
                            NameEn = "Indonesia",
                            NameRu = "Индонезия"
                        },
                        new
                        {
                            Id = 82L,
                            NameEn = "Jordan",
                            NameRu = "Иордания"
                        },
                        new
                        {
                            Id = 83L,
                            NameEn = "Iraq",
                            NameRu = "Ирак"
                        },
                        new
                        {
                            Id = 84L,
                            NameEn = "Iran",
                            NameRu = "Иран"
                        },
                        new
                        {
                            Id = 85L,
                            NameEn = "Ireland",
                            NameRu = "Ирландия"
                        },
                        new
                        {
                            Id = 86L,
                            NameEn = "Iceland",
                            NameRu = "Исландия"
                        },
                        new
                        {
                            Id = 87L,
                            NameEn = "Spain",
                            NameRu = "Испания"
                        },
                        new
                        {
                            Id = 88L,
                            NameEn = "Italy",
                            NameRu = "Италия"
                        },
                        new
                        {
                            Id = 89L,
                            NameEn = "Yemen",
                            NameRu = "Йемен"
                        },
                        new
                        {
                            Id = 90L,
                            NameEn = "Cape Verde",
                            NameRu = "Кабо-Верде"
                        },
                        new
                        {
                            Id = 91L,
                            NameEn = "Cambodia",
                            NameRu = "Камбоджа"
                        },
                        new
                        {
                            Id = 92L,
                            NameEn = "Cameroon",
                            NameRu = "Камерун"
                        },
                        new
                        {
                            Id = 93L,
                            NameEn = "Qatar",
                            NameRu = "Катар"
                        },
                        new
                        {
                            Id = 94L,
                            NameEn = "Kenya",
                            NameRu = "Кения"
                        },
                        new
                        {
                            Id = 95L,
                            NameEn = "Cyprus",
                            NameRu = "Кипр"
                        },
                        new
                        {
                            Id = 96L,
                            NameEn = "Kiribati",
                            NameRu = "Кирибати"
                        },
                        new
                        {
                            Id = 97L,
                            NameEn = "China",
                            NameRu = "Китай"
                        },
                        new
                        {
                            Id = 98L,
                            NameEn = "Colombia",
                            NameRu = "Колумбия"
                        },
                        new
                        {
                            Id = 99L,
                            NameEn = "Comoros",
                            NameRu = "Коморские острова"
                        },
                        new
                        {
                            Id = 100L,
                            NameEn = "Congo",
                            NameRu = "Конго"
                        },
                        new
                        {
                            Id = 101L,
                            NameEn = "Congo Democratic Republic",
                            NameRu = "Демократическая республика Конго"
                        },
                        new
                        {
                            Id = 102L,
                            NameEn = "Costa Rica",
                            NameRu = "Коста Рика"
                        },
                        new
                        {
                            Id = 103L,
                            NameEn = "Cote dʻIvoire",
                            NameRu = "Берег Слоновой Кости"
                        },
                        new
                        {
                            Id = 104L,
                            NameEn = "Cuba",
                            NameRu = "Куба"
                        },
                        new
                        {
                            Id = 105L,
                            NameEn = "Kuwait",
                            NameRu = "Кувейт"
                        },
                        new
                        {
                            Id = 106L,
                            NameEn = "Laos",
                            NameRu = "Лаос"
                        },
                        new
                        {
                            Id = 107L,
                            NameEn = "Lesotho",
                            NameRu = "Лесото"
                        },
                        new
                        {
                            Id = 108L,
                            NameEn = "Liberia",
                            NameRu = "Либерия"
                        },
                        new
                        {
                            Id = 109L,
                            NameEn = "Lebanon",
                            NameRu = "Ливан"
                        },
                        new
                        {
                            Id = 110L,
                            NameEn = "Libya",
                            NameRu = "Ливия"
                        },
                        new
                        {
                            Id = 111L,
                            NameEn = "Liechtenstein",
                            NameRu = "Лихтенштейн"
                        },
                        new
                        {
                            Id = 112L,
                            NameEn = "Luxembourg",
                            NameRu = "Люксембург"
                        },
                        new
                        {
                            Id = 113L,
                            NameEn = "Mauritius",
                            NameRu = "Маврикий"
                        },
                        new
                        {
                            Id = 114L,
                            NameEn = "Mauritania",
                            NameRu = "Мавритания"
                        },
                        new
                        {
                            Id = 115L,
                            NameEn = "Madagascar",
                            NameRu = "Мадагаскар"
                        },
                        new
                        {
                            Id = 116L,
                            NameEn = "Macau",
                            NameRu = "Макао"
                        },
                        new
                        {
                            Id = 117L,
                            NameEn = "Macedonia",
                            NameRu = "Македония"
                        },
                        new
                        {
                            Id = 118L,
                            NameEn = "Malawi",
                            NameRu = "Малави"
                        },
                        new
                        {
                            Id = 119L,
                            NameEn = "Malaysia",
                            NameRu = "Малайзия"
                        },
                        new
                        {
                            Id = 120L,
                            NameEn = "Mali",
                            NameRu = "Мали"
                        },
                        new
                        {
                            Id = 121L,
                            NameEn = "Maldives",
                            NameRu = "Мальдивы"
                        },
                        new
                        {
                            Id = 122L,
                            NameEn = "Malta",
                            NameRu = "Мальта"
                        },
                        new
                        {
                            Id = 123L,
                            NameEn = "Morocco",
                            NameRu = "Марокко"
                        },
                        new
                        {
                            Id = 124L,
                            NameEn = "Martinique",
                            NameRu = "Мартиника"
                        },
                        new
                        {
                            Id = 125L,
                            NameEn = "Marshall Islands",
                            NameRu = "Маршалловы острова"
                        },
                        new
                        {
                            Id = 126L,
                            NameEn = "Mexico",
                            NameRu = "Мексика"
                        },
                        new
                        {
                            Id = 127L,
                            NameEn = "Micronesia, Federated States",
                            NameRu = "Микронезия, Федеративные Штаты"
                        },
                        new
                        {
                            Id = 128L,
                            NameEn = "Mozambique",
                            NameRu = "Мозамбик"
                        },
                        new
                        {
                            Id = 129L,
                            NameEn = "Monaco",
                            NameRu = "Монако"
                        },
                        new
                        {
                            Id = 130L,
                            NameEn = "Mongolia",
                            NameRu = "Монголия"
                        },
                        new
                        {
                            Id = 131L,
                            NameEn = "Montserrat",
                            NameRu = "Монсеррат"
                        },
                        new
                        {
                            Id = 132L,
                            NameEn = "Myanmar",
                            NameRu = "Мьянма"
                        },
                        new
                        {
                            Id = 133L,
                            NameEn = "Namibia",
                            NameRu = "Намибия"
                        },
                        new
                        {
                            Id = 134L,
                            NameEn = "Nauru",
                            NameRu = "Науру"
                        },
                        new
                        {
                            Id = 135L,
                            NameEn = "Nepal",
                            NameRu = "Непал"
                        },
                        new
                        {
                            Id = 136L,
                            NameEn = "Niger",
                            NameRu = "Нигер"
                        },
                        new
                        {
                            Id = 137L,
                            NameEn = "Nigeria",
                            NameRu = "Нигерия"
                        },
                        new
                        {
                            Id = 138L,
                            NameEn = "Curacao",
                            NameRu = "ликер кюрасо"
                        },
                        new
                        {
                            Id = 139L,
                            NameEn = "Netherlands",
                            NameRu = "Нидерланды"
                        },
                        new
                        {
                            Id = 140L,
                            NameEn = "Nicaragua",
                            NameRu = "Никарагуа"
                        },
                        new
                        {
                            Id = 141L,
                            NameEn = "Niue",
                            NameRu = "Ниуэ"
                        },
                        new
                        {
                            Id = 142L,
                            NameEn = "New Zealand",
                            NameRu = "Новая Зеландия"
                        },
                        new
                        {
                            Id = 143L,
                            NameEn = "New Caledonia",
                            NameRu = "Новая Каледония"
                        },
                        new
                        {
                            Id = 144L,
                            NameEn = "Norway",
                            NameRu = "Норвегия"
                        },
                        new
                        {
                            Id = 145L,
                            NameEn = "United Arab Emirates",
                            NameRu = "Объединенные Арабские Эмираты"
                        },
                        new
                        {
                            Id = 146L,
                            NameEn = "Oman",
                            NameRu = "Оман"
                        },
                        new
                        {
                            Id = 147L,
                            NameEn = "Isle Of Man",
                            NameRu = "Остров Мэн"
                        },
                        new
                        {
                            Id = 148L,
                            NameEn = "Norfolk Island",
                            NameRu = "Остров Норфолк"
                        },
                        new
                        {
                            Id = 149L,
                            NameEn = "Cayman Islands",
                            NameRu = "Каймановы острова"
                        },
                        new
                        {
                            Id = 150L,
                            NameEn = "Cook Islands",
                            NameRu = "Острова Кука"
                        },
                        new
                        {
                            Id = 151L,
                            NameEn = "Turks and Caicos Islands",
                            NameRu = "Острова Теркс и Кайкос"
                        },
                        new
                        {
                            Id = 152L,
                            NameEn = "Pakistan",
                            NameRu = "Пакистан"
                        },
                        new
                        {
                            Id = 153L,
                            NameEn = "Palau",
                            NameRu = "Палау"
                        },
                        new
                        {
                            Id = 154L,
                            NameEn = "Palestinian autonomy",
                            NameRu = "Палестинская автономия"
                        },
                        new
                        {
                            Id = 155L,
                            NameEn = "Panama",
                            NameRu = "Панама"
                        },
                        new
                        {
                            Id = 156L,
                            NameEn = "Papua New Guinea",
                            NameRu = "Папуа -Новая Гвинея"
                        },
                        new
                        {
                            Id = 157L,
                            NameEn = "Paraguay",
                            NameRu = "Парагвай"
                        },
                        new
                        {
                            Id = 158L,
                            NameEn = "Peru",
                            NameRu = "Перу"
                        },
                        new
                        {
                            Id = 159L,
                            NameEn = "Pitkern",
                            NameRu = "Pitkern"
                        },
                        new
                        {
                            Id = 160L,
                            NameEn = "Poland",
                            NameRu = "Польша"
                        },
                        new
                        {
                            Id = 161L,
                            NameEn = "Portugal",
                            NameRu = "Португалия"
                        },
                        new
                        {
                            Id = 162L,
                            NameEn = "Puerto rico",
                            NameRu = "Пуэрто-Рико"
                        },
                        new
                        {
                            Id = 163L,
                            NameEn = "Reunion",
                            NameRu = "воссоединение"
                        },
                        new
                        {
                            Id = 164L,
                            NameEn = "Rwanda",
                            NameRu = "Руанда"
                        },
                        new
                        {
                            Id = 165L,
                            NameEn = "Romania",
                            NameRu = "Румыния"
                        },
                        new
                        {
                            Id = 166L,
                            NameEn = "Salvador",
                            NameRu = "Сальвадор"
                        },
                        new
                        {
                            Id = 167L,
                            NameEn = "Samoa",
                            NameRu = "Самоа"
                        },
                        new
                        {
                            Id = 168L,
                            NameEn = "San marino",
                            NameRu = "Сан - Марино"
                        },
                        new
                        {
                            Id = 169L,
                            NameEn = "Sao Tome and Principe",
                            NameRu = "Сан - Томе и Принсипи"
                        },
                        new
                        {
                            Id = 170L,
                            NameEn = "Saudi Arabia",
                            NameRu = "Саудовская Аравия"
                        },
                        new
                        {
                            Id = 171L,
                            NameEn = "Swaziland",
                            NameRu = "Свазиленд"
                        },
                        new
                        {
                            Id = 172L,
                            NameEn = "Saint Helena",
                            NameRu = "Остров Святой Елены"
                        },
                        new
                        {
                            Id = 173L,
                            NameEn = "Democratic People's Republic of Korea",
                            NameRu = "Корейская Народно-Демократическая Республика"
                        },
                        new
                        {
                            Id = 174L,
                            NameEn = "Northern Mariana Islands",
                            NameRu = "Северные Марианские острова"
                        },
                        new
                        {
                            Id = 175L,
                            NameEn = "Seychelles",
                            NameRu = "Сейшельские острова"
                        },
                        new
                        {
                            Id = 176L,
                            NameEn = "Senegal",
                            NameRu = "Сенегал"
                        },
                        new
                        {
                            Id = 177L,
                            NameEn = "St.Vincent",
                            NameRu = "Сент-Винсент"
                        },
                        new
                        {
                            Id = 178L,
                            NameEn = "Saint Kitts and Nevis",
                            NameRu = "Сент - Китс и Невис"
                        },
                        new
                        {
                            Id = 179L,
                            NameEn = "Saint Lucia",
                            NameRu = "Санкт - Люсия"
                        },
                        new
                        {
                            Id = 180L,
                            NameEn = "St.Pierre and Miquelon",
                            NameRu = "Сен-Пьер и Микелон"
                        },
                        new
                        {
                            Id = 181L,
                            NameEn = "Serbia",
                            NameRu = "Сербия"
                        },
                        new
                        {
                            Id = 182L,
                            NameEn = "Singapore",
                            NameRu = "Сингапур"
                        },
                        new
                        {
                            Id = 183L,
                            NameEn = "Syrian Arab Republic",
                            NameRu = "Сирийская Арабская Республика"
                        },
                        new
                        {
                            Id = 184L,
                            NameEn = "Slovakia",
                            NameRu = "Словакия"
                        },
                        new
                        {
                            Id = 185L,
                            NameEn = "Slovenia",
                            NameRu = "Словения"
                        },
                        new
                        {
                            Id = 186L,
                            NameEn = "Solomon islands",
                            NameRu = "Соломоновы острова"
                        },
                        new
                        {
                            Id = 187L,
                            NameEn = "Somalia",
                            NameRu = "Сомали"
                        },
                        new
                        {
                            Id = 188L,
                            NameEn = "Sudan",
                            NameRu = "Судан"
                        },
                        new
                        {
                            Id = 189L,
                            NameEn = "Suriname",
                            NameRu = "Суринам"
                        },
                        new
                        {
                            Id = 190L,
                            NameEn = "Sierra Leone",
                            NameRu = "Сьерра - Леоне"
                        },
                        new
                        {
                            Id = 191L,
                            NameEn = "Thailand",
                            NameRu = "Таиланд"
                        },
                        new
                        {
                            Id = 192L,
                            NameEn = "Taiwan",
                            NameRu = "Тайвань"
                        },
                        new
                        {
                            Id = 193L,
                            NameEn = "Tanzania",
                            NameRu = "Танзания"
                        },
                        new
                        {
                            Id = 194L,
                            NameEn = "Togo",
                            NameRu = "Того"
                        },
                        new
                        {
                            Id = 195L,
                            NameEn = "Tokelau",
                            NameRu = "Токелау"
                        },
                        new
                        {
                            Id = 196L,
                            NameEn = "Tonga",
                            NameRu = "Тонга"
                        },
                        new
                        {
                            Id = 197L,
                            NameEn = "Trinidad and Tobago",
                            NameRu = "Тринидад и Тобаго"
                        },
                        new
                        {
                            Id = 198L,
                            NameEn = "Tuvalu",
                            NameRu = "Тувалу"
                        },
                        new
                        {
                            Id = 199L,
                            NameEn = "Tunisia",
                            NameRu = "Тунис"
                        },
                        new
                        {
                            Id = 200L,
                            NameEn = "Turkey",
                            NameRu = "Турция"
                        },
                        new
                        {
                            Id = 201L,
                            NameEn = "Uganda",
                            NameRu = "Уганда"
                        },
                        new
                        {
                            Id = 202L,
                            NameEn = "Wallis and Futuna",
                            NameRu = "Уоллис и Футуна"
                        },
                        new
                        {
                            Id = 203L,
                            NameEn = "Uruguay",
                            NameRu = "Уругвай"
                        },
                        new
                        {
                            Id = 204L,
                            NameEn = "Faroe islands",
                            NameRu = "Фарерские острова"
                        },
                        new
                        {
                            Id = 205L,
                            NameEn = "Fiji",
                            NameRu = "Фиджи"
                        },
                        new
                        {
                            Id = 206L,
                            NameEn = "Philippines",
                            NameRu = "Филиппины"
                        },
                        new
                        {
                            Id = 207L,
                            NameEn = "Finland",
                            NameRu = "Финляндия"
                        },
                        new
                        {
                            Id = 208L,
                            NameEn = "Falkland islands",
                            NameRu = "Фолклендские острова"
                        },
                        new
                        {
                            Id = 209L,
                            NameEn = "France",
                            NameRu = "Франция"
                        },
                        new
                        {
                            Id = 210L,
                            NameEn = "French Guiana",
                            NameRu = "Французская Гвиана"
                        },
                        new
                        {
                            Id = 211L,
                            NameEn = "French polynesia",
                            NameRu = "Французская Полинезия"
                        },
                        new
                        {
                            Id = 212L,
                            NameEn = "Croatia",
                            NameRu = "Хорватия"
                        },
                        new
                        {
                            Id = 213L,
                            NameEn = "Central African Republic",
                            NameRu = "Центрально-Африканская Республика"
                        },
                        new
                        {
                            Id = 214L,
                            NameEn = "Chad",
                            NameRu = "Чад"
                        },
                        new
                        {
                            Id = 215L,
                            NameEn = "Czech",
                            NameRu = "Чехия"
                        },
                        new
                        {
                            Id = 216L,
                            NameEn = "Chile",
                            NameRu = "Чили"
                        },
                        new
                        {
                            Id = 217L,
                            NameEn = "Switzerland",
                            NameRu = "Швейцария"
                        },
                        new
                        {
                            Id = 218L,
                            NameEn = "Sweden",
                            NameRu = "Швеция"
                        },
                        new
                        {
                            Id = 219L,
                            NameEn = "Svalbard and Jan Mayen",
                            NameRu = "Шпицберген и Ян Майен"
                        },
                        new
                        {
                            Id = 220L,
                            NameEn = "Sri Lanka",
                            NameRu = "Шри-Ланка"
                        },
                        new
                        {
                            Id = 221L,
                            NameEn = "Ecuador",
                            NameRu = "Эквадор"
                        },
                        new
                        {
                            Id = 222L,
                            NameEn = "Equatorial Guinea",
                            NameRu = "Экваториальная Гвинея"
                        },
                        new
                        {
                            Id = 223L,
                            NameEn = "Eritrea",
                            NameRu = "Эритрея"
                        },
                        new
                        {
                            Id = 224L,
                            NameEn = "Ethiopia",
                            NameRu = "Эфиопия"
                        },
                        new
                        {
                            Id = 225L,
                            NameEn = "The Republic of Korea",
                            NameRu = "Республика Корея"
                        },
                        new
                        {
                            Id = 226L,
                            NameEn = "South Africa",
                            NameRu = "Южная Африка"
                        },
                        new
                        {
                            Id = 227L,
                            NameEn = "Jamaica",
                            NameRu = "Ямайка"
                        },
                        new
                        {
                            Id = 228L,
                            NameEn = "Japan",
                            NameRu = "Япония"
                        },
                        new
                        {
                            Id = 229L,
                            NameEn = "Montenegro",
                            NameRu = "Черногория"
                        },
                        new
                        {
                            Id = 230L,
                            NameEn = "Djibouti",
                            NameRu = "Джибути"
                        },
                        new
                        {
                            Id = 231L,
                            NameEn = "South Sudan",
                            NameRu = "Южный Судан"
                        },
                        new
                        {
                            Id = 232L,
                            NameEn = "Vatican",
                            NameRu = "Ватикан"
                        },
                        new
                        {
                            Id = 233L,
                            NameEn = "Sint Maarten",
                            NameRu = "Синт - Мартен"
                        },
                        new
                        {
                            Id = 234L,
                            NameEn = "Bonaire, Sint Eustatius and Saba",
                            NameRu = "Бонэйр, Синт - Эстатиус и Саба"
                        });
                });

            modelBuilder.Entity("Data.Models.TestModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TestModels");
                });

            modelBuilder.Entity("Data.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
